# Generated by Django 3.0.8 on 2020-07-04 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('current_date', models.DateTimeField(default=datetime.datetime(2020, 7, 4, 6, 13, 31, 6257))),
                ('reminder_date', models.DateTimeField(default=datetime.datetime(2020, 7, 4, 6, 13, 31, 6257))),
            ],
        ),
    ]
