# Generated by Django 3.1.4 on 2021-08-06 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindapp', '0005_auto_20210806_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 16, 36, 51, 928179)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 16, 36, 51, 928179)),
        ),
    ]
