# Generated by Django 3.1.4 on 2021-08-07 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindapp', '0006_auto_20210806_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 15, 1, 44, 910398)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 15, 1, 44, 910398)),
        ),
    ]
